### ISSUE TITLE
Объявления в header-файле

### ISSUE THREAD

**Issue by mdportnov** [SlaykSD/OOP_NEW#1]
<b>Хорошим тоном</b> написания программ (в частности: сигнатур функций, имён переменных и классов, и тд) является соблюдение единообразного стиля. Смешанный регистр (начиная с малого) для переменных и методов/функций (вместо "_"-разделителя, заглавных первых букв и тд).
Например, https://habr.com/ru/post/172091/
https://github.com/SlaykSD/OOP_NEW/blob/2f496f80ede5827363cf372a536179824a64f163/LONG/LONG/class_LI.h#L9-L39

Названия <b>констант</b> должны быть записаны в верхнем регистре с нижним подчёркиванием в качестве разделителя.
https://github.com/SlaykSD/OOP_NEW/blob/2f496f80ede5827363cf372a536179824a64f163/LONG/LONG/class_LI.h#L10

Соблюдение <b>одинаковых</b> отступов в комментариях и сигнатурах, учёт кодировки текста (не отображаются комментарии).
https://github.com/SlaykSD/OOP_NEW/blob/2f496f80ede5827363cf372a536179824a64f163/LONG/LONG/class_LI.h#L21-L27

**Comment by SlaykSD** [comment]
Пофиксил
