### ISSUE TITLE
Орфография :(

### ISSUE THREAD

**Issue by mdportnov** [SlaykSD/OOP_NEW#3]
Аналогичная история во всём коде:
https://github.com/SlaykSD/OOP_NEW/blob/2f496f80ede5827363cf372a536179824a64f163/LONG/LONG/class_LI.cpp#L26-L29

**Comment by SlaykSD** [comment]
Май инглиш - итс вери бест инглиш

**Comment by SlaykSD** [comment]
Все орфографические ошибки были пофикшены
